env:
  node: true

extends:
  - 'airbnb-base'
  - 'prettier'

plugins:
  - 'prettier'

parserOptions:
  ecmaVersion: latest

rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  prettier/prettier: "error"
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }] # разрешает подчёркивание в именах только для двух констант